server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:file:/tmp/jpadb1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
bank:
  code: ${BANK_CODE:YSS}
  name: ${BANK_NAME:Yohan Banking Coparation}
bankcode-url:
  map:
    "YSH" : "http://yohans-macbook-pro.local:8081"
    "YSS" : "http://yohans-macbook-pro.local:8082"
    "YSC" : "http://yohans-macbook-pro.local:8083"

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG